### ISSUE TITLE
making distro the default installation process for all

### ISSUE THREAD

**Issue by soumith** [torch/distro#10]
All in all, looks like this distro approach is nicer and less error-prone than the ezinstall script, as well as has the nice ability to work behind firewalled servers. So i am moving this to torch/distro and have made it the default.

Exhibit A: http://torch.ch/docs/getting-started.html#_

cc: @clementfarabet @andresy @koraykv

**Comment by clementfarabet** [comment]
This is much better than the wild ezinstall script that just fetches masters everywhere... What's your strategy to update the submodules in this repo?

**Comment by alexbw** [comment]
Currently all submodules are updated to master on install. This reduces the
effort of stewardship, but relies on a functional master branch on all
packages.
What might be best is having an --update-all flag that gates the upgrade
behavior.
Or, don't update, and use Travis CI to test if modules are installing
properly so that we can be alerted to roll them forward or back.

**Comment by alexbw** [comment]
@clementfarabet, I'm not sure what's best to do here. Whetlab is now using torch daily, and on VMs, s.t. that the install process is occurring daily. As such, I'm happy to look after the submodules, and if updates are necessary, we can use the issue tracker to make sure they get updated in a timely fashion. 

Also, it might be a good kick in the pants to have the Travis CI builds for the torch main repo to use this distribution as an install, or to make our own Travis CI builds.

**Comment by clementfarabet** [comment]
@alexbw thanks for the clarification. So on our side, we use an internal mirror of the entire Torch distribution, and only sync from the github repos ~ monthly. Each time we sync, we run a slew of tests, some of them still manual :-(. The issue is that some regressions are very hard to capture with tests (e.g. code slowdown, or very subtle memory leaks, ...), so I'm a bit scared to be dependent on all these master branches.

I agree with you on Travis though: having better tests across the distribution, and travis builds everywhere would help improve stability.

**Comment by alexbw** [comment]
I've opened an issue to discuss this explicitly in #11. @soumith, let me know if I should tone it down, but I'm happy to take the lead on this problem.
