### ISSUE TITLE
Compilation errors, pretty weird maybe issues with RAM - Arch Linux

### ISSUE THREAD

**Issue by synchro--** [torch/distro#168]
I'm on Arch Linux, following the normal instruction to download Torch. 
In doing bash install-deps; I got this. 
Discussing the issue with some friends we thought it cannot create a temporary file, probably the compilation fill all the space /tmp has. I'll dive into it today.  
This could be the same problem of [issues 167](https://github.com/torch/distro/issues/167)

```    /home/synchro/torch/extra/cutorch/lib/THC/generated/THCTensorMaskedDouble.cu -c -o /home/synchro/torch/extra/cutorch/build/lib/THC/CMakeFiles/THC.dir/generated/./THC_generated_THCTensorMaskedDouble.cu.o -ccbin /usr/bin/clang -m64 -DTHC_EXPORTS -Xcompiler ,"-fPIC","-O3","-DNDEBUG" -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_61,code=compute_61 -DCUDA_HAS_FP16=1 -DNVCC -I/opt/cuda/include -I/home/synchro/torch/install/include -I/home/synchro/torch/install/include/TH -I/opt/cuda/include -I/home/synchro/torch/extra/cutorch/lib/THC/CUDA_SDK_ROOT_DIR-NOTFOUND/common/inc -I/TH -I/home/synchro/torch/extra/cutorch/build/lib/THC
fatbinary fatal   : Could not write file '/tmp/tmpxft_000018c2_00000000-2_THCTensorConv.fatbin.c'
CMake Error at THC_generated_THCTensorConv.cu.o.cmake:267 (message):
  Error generating file
  /home/synchro/torch/extra/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorConv.cu.o

make[2]: **\* [lib/THC/CMakeFiles/THC.dir/build.make:163: lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorConv.cu.o] Error 1
make[2]: **\* Waiting for unfinished jobs....
fatal error: error in backend: IO failure on output stream.
fatal error: error in backend: IO failure on output stream.
CMake Error at THC_generated_THCTensorMathReduceHalf.cu.o.cmake:267 (message):
  Error generating file
  /home/synchro/torch/extra/cutorch/build/lib/THC/CMakeFiles/THC.dir/generated/./THC_generated_THCTensorMathReduceHalf.cu.o

make[2]: **\* [lib/THC/CMakeFiles/THC.dir/build.make:443: lib/THC/CMakeFiles/THC.dir/generated/THC_generated_THCTensorMathReduceHalf.cu.o] Error 1
CMake Error at THC_generated_THCTensorMaskedInt.cu.o.cmake:267 (message):
  Error generating file
  /home/synchro/torch/extra/cutorch/build/lib/THC/CMakeFiles/THC.dir/generated/./THC_generated_THCTensorMaskedInt.cu.o

make[2]: **\* [lib/THC/CMakeFiles/THC.dir/build.make:366: lib/THC/CMakeFiles/THC.dir/generated/THC_generated_THCTensorMaskedInt.cu.o] Error 1
^C
Error: LuaRocks 2.3.0 bug (please report at https://github.com/keplerproject/luarocks/issues).
...o/torch/install/share/lua/5.1/luarocks/fs/unix/tools.lua:44: interrupted!
stack traceback:
    ...o/torch/install/share/lua/5.1/luarocks/fs/unix/tools.lua:44: in function 'execute'
    ...o/torch/install/share/lua/5.1/luarocks/build/command.lua:22: in function 'run'
    ...e/synchro/torch/install/share/lua/5.1/luarocks/build.lua:265: in function 'build_rockspec'
    /home/synchro/torch/install/share/lua/5.1/luarocks/make.lua:82: in function </home/synchro/torch/install/share/lua/5.1/luarocks/make.lua:51>
    [C]: in function 'xpcall'
    ...ro/torch/install/share/lua/5.1/luarocks/command_line.lua:207: in function 'run_command'
    /home/synchro/torch/install/bin/luarocks:35: in main chunk
    [C]: at 0x00404670```

**Comment by soumith** [comment]
someone sent a fix for arch compiles now in master.

**Comment by synchro--** [comment]
Thank you. Meanwhile I used the torch-cuda docker image available at [https://hub.docker.com/r/kaixhin/cuda-torch/](url)

**Comment by synchro--** [comment]
Thank you. Meanwhile I used the docker torch-cuda image available at [https://hub.docker.com/r/kaixhin/cuda-torch/](url)

**Comment by erjie123** [comment]
I have the same problem when I install the torch7.
fatbinary fatal   : Could not write file '/tmp/tmpxft_00005ca8_00000000-2_THCTensorMathCompareTByte.fatbin.c'
/usr/local/cuda-7.5/include/thrust/detail/for_each.inl:72:0: fatal error: when writing output to : No space left on device
 } // end for_each_n()
 ^
compilation terminated.
CMake Error at THC_generated_THCTensorMathCompareTByte.cu.o.cmake:267 (message):
  Error generating file
  /home/xchenmin/torch/extra/cutorch/build/lib/THC/CMakeFiles/THC.dir/generated/./THC_generated_THCTensorMathCompareTByte.cu.o


lib/THC/CMakeFiles/THC.dir/build.make:7747: recipe for target 'lib/THC/CMakeFiles/THC.dir/generated/./THC_generated_THCTensorMathCompareTByte.cu.o' failed
make[2]: *** [lib/THC/CMakeFiles/THC.dir/generated/./THC_generated_THCTensorMathCompareTByte.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMake Error at THC_generated_THCTensorMath.cu.o.cmake:267 (message):
  Error generating file
  /home/xchenmin/torch/extra/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorMath.cu.o


lib/THC/CMakeFiles/THC.dir/build.make:2835: recipe for target 'lib/THC/CMakeFiles/THC.dir/./THC_generated_THCTensorMath.cu.o' failed
make[2]: *** [lib/THC/CMakeFiles/THC.dir/./THC_generated_THCTensorMath.cu.o] Error 1
<built-in>: fatal error: when writing output to : No such file or directory
compilation terminated.
CMake Error at THC_generated_THCTensorMaskedByte.cu.o.cmake:207 (message):
  Error generating
  /home/xchenmin/torch/extra/cutorch/build/lib/THC/CMakeFiles/THC.dir/generated/./THC_generated_THCTensorMaskedByte.cu.o


lib/THC/CMakeFiles/THC.dir/build.make:7779: recipe for target 'lib/THC/CMakeFiles/THC.dir/generated/./THC_generated_THCTensorMaskedByte.cu.o' failed
make[2]: *** [lib/THC/CMakeFiles/THC.dir/generated/./THC_generated_THCTensorMaskedByte.cu.o] Error 1
<built-in>: fatal error: when writing output to : No such file or directory
compilation terminated.
CMake Error at THC_generated_THCTensorSortChar.cu.o.cmake:207 (message):
  Error generating
  /home/xchenmin/torch/extra/cutorch/build/lib/THC/CMakeFiles/THC.dir/generated/./THC_generated_THCTensorSortChar.cu.o


lib/THC/CMakeFiles/THC.dir/build.make:7787: recipe for target 'lib/THC/CMakeFiles/THC.dir/generated/./THC_generated_THCTensorSortChar.cu.o' failed
make[2]: *** [lib/THC/CMakeFiles/THC.dir/generated/./THC_generated_THCTensorSortChar.cu.o] Error 1
/usr/local/cuda-7.5/include/thrust/system/cuda/detail/cub/block/specializations/../../block/../block/specializations/../../warp/specializations/../../thread/thread_load.cuh(286): catastrophic error: error while writing generated C++ file: No space left on device

1 catastrophic error detected in the compilation of "/tmp/tmpxft_00005dfd_00000000-5_THCTensorMathReduceByte.cpp4.ii".
Compilation terminated.
CMake Error at THC_generated_THCTensorMathReduceByte.cu.o.cmake:267 (message):
  Error generating file
  /home/xchenmin/torch/extra/cutorch/build/lib/THC/CMakeFiles/THC.dir/generated/./THC_generated_THCTensorMathReduceByte.cu.o


lib/THC/CMakeFiles/THC.dir/build.make:7771: recipe for target 'lib/THC/CMakeFiles/THC.dir/generated/./THC_generated_THCTensorMathReduceByte.cu.o' failed
make[2]: *** [lib/THC/CMakeFiles/THC.dir/generated/./THC_generated_THCTensorMathReduceByte.cu.o] Error 1
/usr/local/cuda-7.5/include/thrust/detail/scan.inl:64:0: fatal error: when writing output to : No space left on device
 } // end inclusive_scan()
 ^
compilation terminated.
CMake Error at THC_generated_THCTensorMathScan.cu.o.cmake:267 (message):
  Error generating file
  /home/xchenmin/torch/extra/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorMathScan.cu.o


lib/THC/CMakeFiles/THC.dir/build.make:6129: recipe for target 'lib/THC/CMakeFiles/THC.dir/./THC_generated_THCTensorMathScan.cu.o' failed
make[2]: *** [lib/THC/CMakeFiles/THC.dir/./THC_generated_THCTensorMathScan.cu.o] Error 1
In file included from tmpxft_00005db7_00000000-4_THCTensorMathCompareByte.cudafe1.stub.c:1:0:
/tmp/tmpxft_00005db7_00000000-4_THCTensorMathCompareByte.cudafe1.stub.c:344:27: fatal error: error writing to /tmp/cc9XN9PO.s: No space left on device
 #pragma GCC diagnostic pop
                           ^
compilation terminated.
In file included from tmpxft_00005cf8_00000000-4_THCTensorRandom.cudafe1.stub.c:1:0:
/tmp/tmpxft_00005cf8_00000000-4_THCTensorRandom.cudafe1.stub.c:11:27: fatal error: error writing to /tmp/ccitV08l.s: No space left on device
 extern void __device_stub__Z15generate_normalP17curandStateMtgp32iPfdd(struct curandStateMtgp32 *, int, float *, double, double);
                           ^
compilation terminated.
The bug is not reproducible, so it is likely a hardware or OS problem.
CMake Error at THC_generated_THCTensorMathCompareByte.cu.o.cmake:267 (message):
  Error generating file
  /home/xchenmin/torch/extra/cutorch/build/lib/THC/CMakeFiles/THC.dir/generated/./THC_generated_THCTensorMathCompareByte.cu.o


lib/THC/CMakeFiles/THC.dir/build.make:7763: recipe for target 'lib/THC/CMakeFiles/THC.dir/generated/./THC_generated_THCTensorMathCompareByte.cu.o' failed
make[2]: *** [lib/THC/CMakeFiles/THC.dir/generated/./THC_generated_THCTensorMathCompareByte.cu.o] Error 1
The bug is not reproducible, so it is likely a hardware or OS problem.
CMake Error at THC_generated_THCTensorRandom.cu.o.cmake:267 (message):
  Error generating file
  /home/xchenmin/torch/extra/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorRandom.cu.o


lib/THC/CMakeFiles/THC.dir/build.make:7480: recipe for target 'lib/THC/CMakeFiles/THC.dir/./THC_generated_THCTensorRandom.cu.o' failed
make[2]: *** [lib/THC/CMakeFiles/THC.dir/./THC_generated_THCTensorRandom.cu.o] Error 1
In file included from tmpxft_00005cb9_00000000-4_THCTensorSortByte.cudafe1.stub.c:1:0:
/tmp/tmpxft_00005cb9_00000000-4_THCTensorSortByte.cudafe1.stub.c:1046:27: fatal error: error writing to /tmp/cc2mYx0T.s: No space left on device
 #pragma GCC diagnostic pop
                           ^
compilation terminated.
ptxas fatal   : Internal error: writing file
CMake Error at THC_generated_THCTensorTopK.cu.o.cmake:267 (message):
  Error generating file
  /home/xchenmin/torch/extra/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorTopK.cu.o


lib/THC/CMakeFiles/THC.dir/build.make:7699: recipe for target 'lib/THC/CMakeFiles/THC.dir/./THC_generated_THCTensorTopK.cu.o' failed
make[2]: *** [lib/THC/CMakeFiles/THC.dir/./THC_generated_THCTensorTopK.cu.o] Error 1
/usr/local/cuda-7.5/include/thrust/iterator/iterator_facade.h(252) (col. 9): catastrophic error: error while writing generated C file: No space left on device

1 catastrophic error detected in the compilation of "/tmp/tmpxft_00005cdf_00000000-7_THCTensorMode.cpp1.ii".
Compilation terminated.
CMake Error at THC_generated_THCTensorMode.cu.o.cmake:267 (message):
  Error generating file
  /home/xchenmin/torch/extra/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorMode.cu.o


lib/THC/CMakeFiles/THC.dir/build.make:7731: recipe for target 'lib/THC/CMakeFiles/THC.dir/./THC_generated_THCTensorMode.cu.o' failed
make[2]: *** [lib/THC/CMakeFiles/THC.dir/./THC_generated_THCTensorMode.cu.o] Error 1
The bug is not reproducible, so it is likely a hardware or OS problem.
CMake Error at THC_generated_THCTensorSortByte.cu.o.cmake:267 (message):
  Error generating file
  /home/xchenmin/torch/extra/cutorch/build/lib/THC/CMakeFiles/THC.dir/generated/./THC_generated_THCTensorSortByte.cu.o


lib/THC/CMakeFiles/THC.dir/build.make:7739: recipe for target 'lib/THC/CMakeFiles/THC.dir/generated/./THC_generated_THCTensorSortByte.cu.o' failed
make[2]: *** [lib/THC/CMakeFiles/THC.dir/generated/./THC_generated_THCTensorSortByte.cu.o] Error 1
In file included from tmpxft_00005c99_00000000-4_THCTensorMathPointwiseByte.cudafe1.stub.c:1:0:
/tmp/tmpxft_00005c99_00000000-4_THCTensorMathPointwiseByte.cudafe1.stub.c:4770:27: fatal error: error writing to /tmp/ccAHJBF6.s: No space left on device
 #pragma GCC diagnostic pop
                           ^
compilation terminated.
The bug is not reproducible, so it is likely a hardware or OS problem.
CMake Error at THC_generated_THCTensorMathPointwiseByte.cu.o.cmake:267 (message):
  Error generating file
  /home/xchenmin/torch/extra/cutorch/build/lib/THC/CMakeFiles/THC.dir/generated/./THC_generated_THCTensorMathPointwiseByte.cu.o


lib/THC/CMakeFiles/THC.dir/build.make:7755: recipe for target 'lib/THC/CMakeFiles/THC.dir/generated/./THC_generated_THCTensorMathPointwiseByte.cu.o' failed
make[2]: *** [lib/THC/CMakeFiles/THC.dir/generated/./THC_generated_THCTensorMathPointwiseByte.cu.o] Error 1
CMakeFiles/Makefile2:156: recipe for target 'lib/THC/CMakeFiles/THC.dir/all' failed
make[1]: *** [lib/THC/CMakeFiles/THC.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

Error: Build error: Failed building.
And I don't know how to address it.
